- hosts: webservers
  tasks:
  - name: "install GIT"
    ansible.builtin.apt:
      name: git
      state: present
      update_cache: yes
    become: true
    tags: tgit
  - name: "install tar"
    ansible.builtin.apt:
      name: e3
      state: present
      update_cache: yes
    become: true
    tags: tema

