- hosts: webservers
  tasks:
  - name: "install GIT"
    ansible.builtin.apt:
      name: git
      state: present
      update_cache: yes
    become: true

  - name: "install tar"
    ansible.builtin.apt:
      name: e3
      state: present
      update_cache: yes
    become: true

  - name: add test users
    ansible.builtin.user:
      name: "{{ item.name }}"
      state: present
      groups: "{{ item.groups }}"
    become: yes
    loop: "{{ users }}"

  - name: "copy GIT config"
    ansible.builtin.template:
      src: ~/XL-DevOps-VR/gitconfig
      dest: "/home/{{item.name}}/.gitconfig"
    become: yes
    loop: "{{ users }}"

