- hosts: webservers
  vars:
    root_dir: /home/vagrant/XL-DevOps-VR/playbook
    nginx_port: 8080
  tasks:
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
      become: yes

    - name: copy html file
      ansible.builtin.copy:
        src: "{{root_dir}}/index.html"
        dest: /usr/share/nginx/html/index.html
      become: yes

    - name: update nginx config
      ansible.builtin.template:
        src: "{{root_dir}}/nginx.conf"
        dest: /etc/nginx/nginx.conf
      notify:
        - restart nginx
      become: yes

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: yes
















